### ISSUE TITLE
issue with merge_netsim_scenarios

### ISSUE THREAD

**Issue by AdrienLeGuillou** [EpiModel/EpiModelHPC#41]
starting an issue from @clchand23 message:

```
> merge_netsim_scenarios(here("data", "intermediate", "scenarios"),
+                        "scenarios_merged")
Error in names(z[[other.x[j]]]) <- newnames : 
  attempt to set an attribute on NULL
```

**Comment by sgoodreau** [comment]
@AdrienLeGuillou Do you think this may be the same underlying issue that is in #40 ?

**Comment by AdrienLeGuillou** [comment]
@sgoodreau yes, I am pretty sure it is. I'll look into it today

**Comment by AdrienLeGuillou** [comment]
Actually it may be  different issue.
@clchand23 can you point me to the code that produced that error? I cannot replicate it on my projects

**Comment by AdrienLeGuillou** [comment]
sorry I was unclear, I need to see the code that produced the simulations. To see if the issue is with the function itself or in the code saving the sims.

**Comment by clchand23** [comment]
The simulations were created using the EpiModelHIV intervention scenarios workflow scripts and were downloaded directly from the HPC

**Comment by smjenness** [comment]
@clchand23 : this is now merged in and you can update EpiModelHPC with `remotes::install_github("EpiModel/EpiModelHPC@main")`
